/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include <stdint.h>

#include "STM32F446xx.h"
#include "ErrTypes.h"
#include "STD_MACROS.h"

#include "SYSTIC_interface.h"
#include "GPIO_interface.h"
#include "RCC_interface.h"
#include "SYSCFG_interface.h"
#include "SPI_interface.h"
#include "USART_intreface.h"
#include "NVIC_interface.h"
#include "TFT_interface.h"
#include "TFT_Image.h"

#include "SYS_init.h"

extern USART_Handle_t USART_2;
extern SPI_Config_t SPI1 ;
uint8_t Global_USART_u8RXData = 0XFF;

uint8_t Global_u8Current = 0;
uint8_t Global_u8Playing = 0;
uint8_t Global_u8Flag    = 0;

int main(void)
{
  SYS_vinit();
  HTFT_vDisplay(&SPI1, arr0);
  SYSTIC_vDelayMs(1000);
  while(1)
  {
    switch (Global_USART_u8RXData)
    {
    case '1':
      Global_u8Current ^= (1 << 0);
      Global_USART_u8RXData = 0XFF;
      break;
    case '2':
      Global_u8Playing ^= (1 << 0);
      Global_USART_u8RXData = 0XFF;
      break;
    case '3':
      Global_u8Current ^= (1 << 0);
      Global_USART_u8RXData = 0XFF;
      break;
    }
    if (Global_u8Flag)
    {
      if ((Global_u8Current == 0) && (Global_u8Playing == 0))
      {
        HTFT_vDisplay(&SPI1, arr2);
      }
      else if ((Global_u8Current == 0) && (Global_u8Playing == 1))
      {
        HTFT_vDisplay(&SPI1, arr1);
      }
      else if ((Global_u8Current == 1) && (Global_u8Playing == 0))
      {
        HTFT_vDisplay(&SPI1, arr4);
      }
      else if ((Global_u8Current == 1) && (Global_u8Playing == 1))
      {
        HTFT_vDisplay(&SPI1, arr3);
      }
      else
      {

      }
      Global_u8Flag = 0;
    }

  }
}

void USART_RXCMP(void)
{
  USART_enumReceive((USART_Config_t *)&USART_2, &Global_USART_u8RXData);
  Global_u8Flag = 1;
  SYSTIC_vDelayMs(500);
}
