/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include "STM32F446xx.h"
#include "STD_MACROS.h"
#include "ErrTypes.h"
#include "song.h"
#include "song2.h"
#include "song3.h"

#include "RCC_interface.h"
#include "GPIO_interface.h"
#include "SYSTIC_interface.h"
#include "NVIC_interface.h"
#include "EXTI_interface.h"
#include "SYSCFG_interface.h"
#include "SYS_init.h"

unsigned int i_loop = 0 , End = 0 , playing_now = 0;
unsigned char Playing_arr[83000] = {0};
unsigned int playing_flag = 0;

extern EXTI_LineConfig_t NEXT_Line;
extern EXTI_LineConfig_t PAUSE_Line;
extern EXTI_LineConfig_t PREVIOUS_Line;

extern uint8_t Global_u8IRVal;

int main(void)
{

  SYS_init();

  memcpy(Playing_arr, son1_raw, sizeof(son1_raw));
  End = 148316;
  while(1)
  {
    if (playing_flag == 1)
    {
      for(i_loop = 0; i_loop < End; i_loop++)
      {
        GPIO_enumWrite8PinsVal(GPIO_PORTC, GPIO_PIN0, Playing_arr[i_loop]);
        SYSTIC_vDelayUs(232);
        if (playing_flag == 0)
        {
          break;
        }
        else
        {

        }
      }
    }
    else
    {
      if (Global_u8IRVal == 64)
      {
        EXTI_vSwIntEvent(&NEXT_Line);
        Global_u8IRVal = 0xff;
      }
      else if (Global_u8IRVal == 67)
      {
        EXTI_vSwIntEvent(&PAUSE_Line);
        Global_u8IRVal = 0xff;
      }
      else if (Global_u8IRVal == 68)
      {
        EXTI_vSwIntEvent(&PREVIOUS_Line);
        Global_u8IRVal = 0xff;
      }
      else
      {

      }
    }
  }
}

void NEXT(void)
{
  if (playing_now == 0)
  {
    playing_now = 1;
    memcpy(Playing_arr, son2_raw, sizeof(son2_raw));
    End = 69778;
    i_loop = 0;
  }
  else if (playing_now == 1)
  {
    playing_now = 2;
    memcpy(Playing_arr, son3_raw, sizeof(son3_raw));
    End = 82302;
    i_loop = 0;
  }
  else if (playing_now == 2)
  {
    playing_now = 0;
    memcpy(Playing_arr, son1_raw, sizeof(son1_raw));
    End = 71030;
    i_loop = 0;
  }
}

void PAUSE_RESUME(void)
{
  if(playing_flag == 0)
  {
    playing_flag = 1;
  }
  else if(playing_flag == 1)
  {
    playing_flag = 0;
  }
}

void PREVIOUS(void)
{
  if (playing_now == 0)
  {
    playing_now = 2;
    memcpy(Playing_arr, son3_raw, sizeof(son3_raw));
    End = 82302;
    i_loop = 0;
  }
  else if (playing_now == 1)
  {
    playing_now = 0;
    memcpy(Playing_arr, son1_raw, sizeof(son1_raw));
    End = 15904;
    i_loop = 0;
  }
  else if (playing_now == 2)
  {
    playing_now = 1;
    memcpy(Playing_arr, son2_raw, sizeof(son2_raw));
    End = 69778;
    i_loop = 0;
  }
}
